export const layoutsTypes = {
  SELECT_LAYOUT: 'SELECT_LAYOUT',
  FETCH_LAYOUTS_REQUEST: 'FETCH_LAYOUTS_REQUEST',
  FETCH_LAYOUTS_SUCCESS: 'FETCH_LAYOUTS_SUCCESS',
  FETCH_LAYOUTS_FAILURE: 'FETCH_LAYOUTS_FAILURE'
}
