export const layoutsTypes = {
  SELECT_LAYOUT: 'SELECT_LAYOUT',
  LOAD_LAYOUTS_REQUEST: 'LOAD_LAYOUTS_REQUEST',
  LOAD_LAYOUTS_SUCCESS: 'LOAD_LAYOUTS_SUCCESS',
  LOAD_LAYOUTS_FAILURE: 'LOAD_LAYOUTS_FAILURE'
}
