export const SELECT_LAYOUT = 'SELECT_LAYOUT'
export const RESET_POSITIONS = 'RESET_POSITIONS'
export const ADD_PLAYER_POSITION = 'ADD_PLAYER_POSITION'
export const REMOVE_PLAYER_POSITION = 'REMOVE_PLAYER_POSITION'

export const ADD_PLAYER_REQUEST = 'ADD_PLAYER_REQUEST'
export const ADD_PLAYER_SUCCESS = 'ADD_PLAYER_SUCCESS'
export const ADD_PLAYER_FAILURE = 'ADD_PLAYER_FAILURE'

export const FETCH_LAYOUTS_REQUEST = 'FETCH_LAYOUTS_REQUEST'
export const FETCH_LAYOUTS_SUCCESS = 'FETCH_LAYOUTS_SUCCESS'
export const FETCH_LAYOUTS_FAILURE = 'FETCH_LAYOUTS_FAILURE'
