export const shareCodeTypes = {
  NEW_SHARE_CODE: 'NEW_SHARE_CODE',
  NEW_SHARE_CODE_SUCCESS: 'NEW_SHARE_CODE_SUCCESS',
  NEW_SHARE_CODE_FAILURE: 'NEW_SHARE_CODE_FAILURE',

  LOAD_SHARE_CODE: 'LOAD_SHARE_CODE',
  LOAD_SHARE_CODE_SUCCESS: 'LOAD_SHARE_CODE_SUCCESS',
  LOAD_SHARE_CODE_FAILURE: 'LOAD_SHARE_CODE_FAILURE'
}
