export const positionsTypes = {
  RESET_POSITIONS: 'RESET_POSITIONS',
  ADD_PLAYER_POSITION: 'ADD_PLAYER_POSITION',
  REMOVE_PLAYER_POSITION: 'REMOVE_PLAYER_POSITION',
  CLEAN_PLAYER_POSITION: 'CLEAN_PLAYER_POSITION'
}
