export const positionsTypes = {
  RESET_POSITIONS: 'RESET_POSITIONS',
  CLEAN_PLAYER_POSITION: 'CLEAN_PLAYER_POSITION',
  ADD_PLAYER_POSITION: 'ADD_PLAYER_POSITION',
  UPDATE_POSITION: 'UPDATE_POSITION',
  SWITCH_POSITION: 'SWITCH_POSITION'
}
