export const SELECT_LAYOUT = 'SELECT_LAYOUT'

export const FETCH_LAYOUTS_REQUEST = 'FETCH_LAYOUTS_REQUEST'
export const FETCH_LAYOUTS_SUCCESS = 'FETCH_LAYOUTS_SUCCESS'
export const FETCH_LAYOUTS_FAILURE = 'FETCH_LAYOUTS_FAILURE'
