export const SELECT_LAYOUT = 'SELECT_LAYOUT'
export const RESET_POSITIONS = 'RESET_POSITIONS'
export const ADD_PLAYER_POSITION = 'ADD_PLAYER_POSITION'
export const REMOVE_PLAYER_POSITION = 'REMOVE_PLAYER_POSITION'
export const CLEAN_PLAYER_POSITION = 'CLEAN_PLAYER_POSITION'

export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'

export const FETCH_LAYOUTS_REQUEST = 'FETCH_LAYOUTS_REQUEST'
export const FETCH_LAYOUTS_SUCCESS = 'FETCH_LAYOUTS_SUCCESS'
export const FETCH_LAYOUTS_FAILURE = 'FETCH_LAYOUTS_FAILURE'
