export const playersTypes = {
  ADD_PLAYER_REQUEST: 'ADD_PLAYER_REQUEST',
  ADD_PLAYER_SUCCESS: 'ADD_PLAYER_SUCCESS',
  ADD_PLAYER_FAILURE: 'ADD_PLAYER_FAILURE',

  LOAD_PLAYERS_REQUEST: 'LOAD_PLAYERS_REQUEST',
  LOAD_PLAYERS_SUCCESS: 'LOAD_PLAYERS_SUCCESS',
  LOAD_PLAYERS_FAILURE: 'LOAD_PLAYERS_FAILURE'
}
