export const playersTypes = {
  ADD_PLAYER_REQUEST: 'ADD_PLAYER_REQUEST',
  ADD_PLAYER_SUCCESS: 'ADD_PLAYER_SUCCESS',
  ADD_PLAYER_FAILURE: 'ADD_PLAYER_FAILURE',

  LOAD_PLAYERS_REQUEST: 'LOAD_PLAYERS_REQUEST',
  LOAD_PLAYERS_SUCCESS: 'LOAD_PLAYERS_SUCCESS',
  LOAD_PLAYERS_FAILURE: 'LOAD_PLAYERS_FAILURE',

  UPDATE_PLAYERS_REQUEST: 'UPDATE_PLAYERS_REQUEST',
  UPDATE_PLAYERS_SUCCESS: 'UPDATE_PLAYERS_SUCCESS',
  UPDATE_PLAYERS_FAILURE: 'UPDATE_PLAYERS_FAILURE',

  REMOVE_PLAYERS_REQUEST: 'REMOVE_PLAYERS_REQUEST',
  REMOVE_PLAYERS_SUCCESS: 'REMOVE_PLAYERS_SUCCESS',
  REMOVE_PLAYERS_FAILURE: 'REMOVE_PLAYERS_FAILURE'
}
